# Generated by Django 6.0.7 on 2026-08-02 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('pourcentage', models.PositiveSmallIntegerField(default=0, help_text='Réduction en pourcentage (ex: 10 = -10%)')),
                ('montant', models.DecimalField(decimal_places=2, default=0, help_text='Réduction en montant fixe (FCFA). Ignoré si pourcentage > 0.', max_digits=10)),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('utilisations_max', models.PositiveIntegerField(default=0, help_text='0 = illimité')),
                ('utilisations', models.PositiveIntegerField(default=0, editable=False)),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name='Expiration')),
            ],
            options={
                'verbose_name': 'Code promo',
                'verbose_name_plural': 'Codes promo',
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email (pour confirmation)'),
        ),
        migrations.AddField(
            model_name='commande',
            name='frais_livraison',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commande',
            name='methode_paiement',
            field=models.CharField(choices=[('a_la_livraison', 'Paiement à la livraison'), ('mobile_money', 'Mobile Money (confirmation par appel)')], default='a_la_livraison', max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.AddField(
            model_name='commande',
            name='reduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commande',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='commande',
            name='code_promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commandes.codepromo', verbose_name='Code promo appliqué'),
        ),
    ]
