# Generated by Django 6.1.1 on 2026-09-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_codepromo_commande_email_commande_frais_livraison_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='methode_paiement',
            field=models.CharField(choices=[('a_la_livraison', 'Paiement à la livraison'), ('mobile_money', 'Mobile Money (Orange/Moov/MTN via CinetPay)'), ('carte_bancaire', 'Carte Bancaire (Stripe/CinetPay)')], default='a_la_livraison', max_length=20, verbose_name='Méthode de paiement'),
        ),
    ]
