# Generated by Django 6.1.1 on 2026-09-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_alter_commande_methode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='paiement_statut',
            field=models.CharField(choices=[('non_requis', 'Paiement à la livraison'), ('en_attente', 'Paiement en attente'), ('paye', 'Payé en ligne'), ('echoue', 'Paiement échoué')], default='non_requis', max_length=20, verbose_name='Statut du paiement en ligne'),
        ),
        migrations.AddField(
            model_name='commande',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='commande',
            name='methode_paiement',
            field=models.CharField(choices=[('a_la_livraison', 'Paiement à la livraison'), ('mobile_money', 'Mobile Money (Orange/Moov/MTN via CinetPay)'), ('carte_bancaire', 'Carte bancaire (via CinetPay)')], default='a_la_livraison', max_length=20, verbose_name='Méthode de paiement'),
        ),
    ]
