"""
Django settings for techshop project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-a-changer-avant-production')
DEBUG = os.getenv('DEBUG', 'False').lower() in ('1', 'true', 'yes', 'on')
if not DEBUG and SECRET_KEY.startswith('django-insecure'):
    raise RuntimeError("SECRET_KEY doit être défini dans .env quand DEBUG=False.")
ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'rest_framework',
    'produits',
    'commandes',
    'dashboard',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # doit être juste après SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'techshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'commandes.context_processors.panier_context',
                'produits.context_processors.favoris_context',
                'dashboard.context_processors.site_settings',
                'dashboard.context_processors.stock_faible',
                'dashboard.context_processors.avis_attente',
                'dashboard.context_processors.droits_dashboard',
            ]
        },
    },
]

WSGI_APPLICATION = 'techshop.wsgi.application'

# ── Base de données ──────────────────────────────────────────────────────────
# • DEBUG=True  → SQLite (développement, zéro config)
# • DEBUG=False → PostgreSQL via DATABASE_URL (production / Coolify)
# • DATABASE_URL défini → force PostgreSQL même si DEBUG=True
_db_url = os.getenv('DATABASE_URL', '').strip()

# Correction automatique si le schéma est manquant (ex: "://" au lieu de "postgres://")
if _db_url and not _db_url.startswith(('postgres://', 'postgresql://')):
    if _db_url.startswith('://'):
        _db_url = 'postgres' + _db_url

if _db_url:
    DATABASES = {'default': dj_database_url.parse(_db_url, conn_max_age=600)}
elif DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    raise RuntimeError(
        "DATABASE_URL doit être défini en production (DEBUG=False). "
        "Exemple : postgres://user:pass@host:5432/dbname"
    )


AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Africa/Abidjan'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# WhiteNoise : sert et compresse les fichiers statiques en production
# CompressedStaticFilesStorage = pas de manifest requis (plus robuste au build)
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}

# Configuration email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('1', 'true', 'yes', 'on')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
# Les mots de passe d'application Gmail s'affichent avec des espaces
# ("xxxx xxxx xxxx xxxx") : on les retire car SMTP les refuse parfois.
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '').replace(' ', '')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_TIMEOUT = 15

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = 'dashboard:login'
LOGIN_REDIRECT_URL = 'dashboard:index'

# Cache : Redis si REDIS_URL est défini et que le module redis est installé,
# sinon mémoire locale (ce qui évite un crash 500 si redis est indisponible).
redis_disponible = False
if os.getenv('REDIS_URL'):
    try:
        import redis  # noqa: F401
        redis_disponible = True
    except ImportError:
        redis_disponible = False

if redis_disponible:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': os.getenv('REDIS_URL'),
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'techshop-cache',
        }
    }

# Derrière Nginx : faire confiance à X-Forwarded-Proto / X-Real-IP
USE_PROXY_HEADERS = os.getenv('USE_PROXY_HEADERS', 'False').lower() in ('1', 'true', 'yes', 'on')
if USE_PROXY_HEADERS:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Paiement en ligne CinetPay (laisser vide = option désactivée dans le tunnel de commande)
CINETPAY_API_KEY = os.getenv('CINETPAY_API_KEY', '')
CINETPAY_SITE_ID = os.getenv('CINETPAY_SITE_ID', '')
CINETPAY_ACTIF = bool(CINETPAY_API_KEY and CINETPAY_SITE_ID)
SITE_URL = os.getenv('SITE_URL', '').rstrip('/')

# API JSON consommée par le front React (dossier frontend/)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ['api.auth.SessionCsrfAuthentication'],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.AllowAny'],
    'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer'],
    'COERCE_DECIMAL_TO_STRING': False,
}
# URL publique du front React (pour les retours de paiement) ; vide = même domaine
FRONTEND_URL = os.getenv('FRONTEND_URL', '').rstrip('/')
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SECURE_REFERRER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'

# Sécurité production (activé quand DEBUG=False)
if not DEBUG:
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    if os.getenv('USE_HTTPS', 'False').lower() in ('1', 'true', 'yes', 'on'):
        SECURE_SSL_REDIRECT = True
        SESSION_COOKIE_SECURE = True
        CSRF_COOKIE_SECURE = True
        SECURE_HSTS_SECONDS = 31536000
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True

# Tests plus rapides : hachage de mot de passe léger (jamais utilisé en exploitation)
if 'test' in sys.argv[1:2]:
    PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher']
