# Generated by Django 6.0.7 on 2026-07-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('site_nom', models.CharField(default='TechShop', max_length=100)),
                ('site_description', models.CharField(blank=True, default='Ordinateurs & accessoires', max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Logo du site (PNG recommandé)', null=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, help_text='Icône du site (32x32px)', null=True, upload_to='settings/')),
                ('accent_couleur', models.CharField(default='#2563eb', max_length=7, verbose_name='Couleur principale')),
                ('accent_sombre', models.CharField(default='#1d4ed8', max_length=7, verbose_name='Couleur foncée')),
                ('surface_couleur', models.CharField(default='#f8fafc', max_length=7, verbose_name='Couleur de surface')),
                ('monnaie_symbole', models.CharField(default='FCFA', max_length=10, verbose_name='Symbole monétaire')),
                ('monnaie_code', models.CharField(default='XOF', max_length=3, verbose_name='Code ISO')),
                ('telephone', models.CharField(blank=True, default='', max_length=50)),
                ('adresse', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('footer_texte', models.CharField(blank=True, default='Paiement à la livraison sur Abidjan.', max_length=255)),
                ('copyright_texte', models.CharField(blank=True, default='TechShop — Ordinateurs & accessoires.', max_length=255)),
                ('mode_sombre_defaut', models.BooleanField(default=False, verbose_name='Mode sombre par défaut')),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
