# Generated by Django 6.0.7 on 2026-07-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='banniere',
            field=models.ImageField(blank=True, help_text='Image bannière 1200x400px', null=True, upload_to='settings/'),
        ),
    ]
