# Generated by Django 6.0.7 on 2026-07-26 04:27

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_sitesettings_banniere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='banniere',
            field=models.ImageField(blank=True, help_text='Image bannière 1200x400px', null=True, upload_to='settings/', validators=[dashboard.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Icône du site (32x32px)', null=True, upload_to='settings/', validators=[dashboard.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo du site (PNG recommandé)', null=True, upload_to='settings/', validators=[dashboard.models.validate_image_file]),
        ),
    ]
