# Generated by Django 6.0.7 on 2026-08-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_sitesettings_banniere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='livraison_gratuite_des',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 = jamais de livraison gratuite.', max_digits=10, verbose_name='Livraison gratuite à partir de (FCFA)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='livraison_prix_fixe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de livraison fixes (FCFA)'),
        ),
    ]
