# Generated by Django 6.1.1 on 2026-09-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_sitesettings_livraison_gratuite_des_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(default='✓', max_length=8, verbose_name='Icône (emoji)')),
                ('titre', models.CharField(max_length=80)),
                ('texte', models.CharField(blank=True, max_length=160)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Engagement',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='apropos_texte',
            field=models.TextField(blank=True, default="Votre boutique en ligne de référence pour le matériel informatique : ordinateurs portables et de bureau, PC gamer, composants et accessoires.\n\nNous sélectionnons avec soin des produits authentiques des plus grandes marques au meilleur prix, avec la garantie d'un service après-vente sérieux.\n\nCommandez en quelques clics : paiement à la livraison ou Mobile Money, et livraison rapide.", help_text='Séparez les paragraphes par une ligne vide.', verbose_name='Page « À propos » : texte'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_bouton',
            field=models.CharField(default='Découvrir la boutique', max_length=40, verbose_name='Bandeau : bouton'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_texte',
            field=models.CharField(blank=True, default='Ordinateurs, accessoires et composants garantis, livrés au meilleur prix.', max_length=255, verbose_name='Bandeau : texte'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_titre',
            field=models.CharField(default='Le meilleur du', max_length=120, verbose_name='Bandeau : titre'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_titre_accent',
            field=models.CharField(blank=True, default='matériel informatique', max_length=120, verbose_name='Bandeau : fin du titre (mise en couleur)'),
        ),
    ]
