# Generated by Django 6.0.7 on 2026-07-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='marque',
            field=models.CharField(blank=True, choices=[('hp', 'HP'), ('dell', 'Dell'), ('lenovo', 'Lenovo'), ('apple', 'Apple'), ('asus', 'Asus'), ('acer', 'Acer'), ('samsung', 'Samsung'), ('microsoft', 'Microsoft'), ('autre', 'Autre')], max_length=50),
        ),
    ]
