# Generated by Django 6.0.7 on 2026-07-22 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_imageproduit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionAccueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la section')),
                ('type_section', models.CharField(choices=[('meilleures_ventes', 'Meilleures ventes'), ('nouveautes', 'Nouveautés'), ('categorie', 'Par catégorie'), ('marque', 'Par marque'), ('personnalise', 'Produits personnalisés')], max_length=50, verbose_name='Type de section')),
                ('marque', models.CharField(blank=True, choices=[('hp', 'HP'), ('dell', 'Dell'), ('lenovo', 'Lenovo'), ('apple', 'Apple'), ('asus', 'Asus'), ('acer', 'Acer'), ('samsung', 'Samsung'), ('microsoft', 'Microsoft'), ('autre', 'Autre')], max_length=50, verbose_name='Marque (si type = Par marque)')),
                ('max_produits', models.PositiveSmallIntegerField(default=8, verbose_name='Nombre max de produits')),
                ('afficher_voir_plus', models.BooleanField(default=True, verbose_name="Afficher 'Voir plus'")),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.categorie', verbose_name="Catégorie (si type = Par catégorie)")),
            ],
            options={
                'verbose_name': 'Section accueil',
                'verbose_name_plural': 'Sections accueil',
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='sectionaccueil',
            name='produits_personnalises',
            field=models.ManyToManyField(blank=True, to='produits.produit', verbose_name='Produits (si type = Personnalisés)'),
        ),
    ]
