# Generated by Django 6.0.7 on 2026-07-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_sectionaccueil'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_barre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix barré (promotion)'),
        ),
    ]
