# Generated by Django 6.0.7 on 2026-07-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0005_produit_prix_barre'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoMarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(choices=[('hp', 'HP'), ('dell', 'Dell'), ('lenovo', 'Lenovo'), ('apple', 'Apple'), ('asus', 'Asus'), ('acer', 'Acer'), ('samsung', 'Samsung'), ('microsoft', 'Microsoft'), ('autre', 'Autre')], max_length=50, unique=True, verbose_name='Marque')),
                ('photo', models.ImageField(upload_to='marques/', verbose_name='Logo / photo de la marque')),
            ],
            options={
                'verbose_name': 'Logo de marque',
                'verbose_name_plural': 'Logos de marques',
                'ordering': ['marque'],
            },
        ),
    ]
