# Generated by Django 6.0.7 on 2026-08-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0006_logomarque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='a_la_une',
            field=models.BooleanField(default=False, help_text='Cochez pour afficher ce produit en permanence dans la section « À la une » de la boutique.', verbose_name='Produit à la une (section statique)'),
        ),
    ]
