# Generated by Django 6.0.7 on 2026-08-02 03:32

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0008_avis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduit',
            name='image',
            field=models.ImageField(upload_to='produits/galerie/', validators=[dashboard.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/', validators=[dashboard.models.validate_image_file]),
        ),
    ]
