# Generated by Django 6.0.7 on 2026-08-16 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0009_alter_imageproduit_image_alter_produit_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionaccueil',
            name='type_section',
            field=models.CharField(choices=[('meilleures_ventes', 'Meilleures ventes'), ('nouveautes', 'Nouveautés'), ('plus_aimes', 'Produits les plus aimés'), ('categorie', 'Par catégorie'), ('marque', 'Par marque'), ('personnalise', 'Produits personnalisés')], max_length=50, verbose_name='Type de section'),
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='produits.produit')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favoris', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'constraints': [models.UniqueConstraint(condition=models.Q(('session_id__gt', '')), fields=('produit', 'session_id'), name='unique_favori_session'), models.UniqueConstraint(condition=models.Q(('utilisateur__isnull', False)), fields=('produit', 'utilisateur'), name='unique_favori_utilisateur')],
            },
        ),
    ]
